# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memoria < Formula
  desc "A terminal-based note-taking app with full-text search, git sync, and a TUI"
  homepage "https://github.com/cassiomarques/memoria"
  version "0.15.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cassiomarques/memoria/releases/download/v0.15.3/memoria_0.15.3_darwin_amd64.tar.gz"
      sha256 "a8ece7152b335794cd31035d33e6ae8356959375d1aa7579cdbdb2812def14af"

      define_method(:install) do
        bin.install "memoria"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cassiomarques/memoria/releases/download/v0.15.3/memoria_0.15.3_darwin_arm64.tar.gz"
      sha256 "db98b1603a421f953a011582d203d7450372eaadfdbc35089d87631f208b5e4a"

      define_method(:install) do
        bin.install "memoria"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cassiomarques/memoria/releases/download/v0.15.3/memoria_0.15.3_linux_amd64.tar.gz"
      sha256 "a2d2b56c7e316fbc524c986ccb05d51ab949877fa88f2f14518d5ad41d01e5f1"
      define_method(:install) do
        bin.install "memoria"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cassiomarques/memoria/releases/download/v0.15.3/memoria_0.15.3_linux_arm64.tar.gz"
      sha256 "a475b887aa0ca6a75742451042a22d084df392dc48ba514f4587b627e42af520"
      define_method(:install) do
        bin.install "memoria"
      end
    end
  end

  test do
    system "#{bin}/memoria", "--version"
  end
end
