# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memoria < Formula
  desc "A terminal-based note-taking app with full-text search, git sync, and a TUI"
  homepage "https://github.com/cassiomarques/memoria"
  version "0.2.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cassiomarques/memoria/releases/download/v0.2.6/memoria_0.2.6_darwin_amd64.tar.gz"
      sha256 "751091ba0b045979121fbd6d630a36462710e7f8ccd9e882b61e73d2f36838e4"

      define_method(:install) do
        bin.install "memoria"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cassiomarques/memoria/releases/download/v0.2.6/memoria_0.2.6_darwin_arm64.tar.gz"
      sha256 "d808db13676ce070fa224e179d2f407e295ef81266e53ab781955b6c24ad0f30"

      define_method(:install) do
        bin.install "memoria"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cassiomarques/memoria/releases/download/v0.2.6/memoria_0.2.6_linux_amd64.tar.gz"
      sha256 "82e4f174cb51dd08e5cd0056d276f6f5d6e377a90d5c5fa1eae7947c4fab2c78"
      define_method(:install) do
        bin.install "memoria"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cassiomarques/memoria/releases/download/v0.2.6/memoria_0.2.6_linux_arm64.tar.gz"
      sha256 "cfcc97fc82e62b85ad74c5e77f6398a0fc3c4aa3afde60d23cd8a7b372279c62"
      define_method(:install) do
        bin.install "memoria"
      end
    end
  end

  test do
    system "#{bin}/memoria", "--version"
  end
end
